// Query TypeMap
import '@sanity/client';

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Activity = {
  _id: string;
  _type: 'activity';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  destination?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'destination';
  };
  categories?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  description?: string;
  price?: number;
  currency?: 'IDR' | 'USD' | 'AUD';
  duration?: string;
  meetingPoint?: string;
  highlights?: Array<string>;
  whatToBring?: Array<string>;
  image?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  isPopular?: boolean;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Destination = {
  _id: string;
  _type: 'destination';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Activity
  | SanityImageCrop
  | SanityImageHotspot
  | Destination
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/(frontend)/activity/[slug]/page.tsx
// Variable: QUERY_ACTIVITY
// Query: *[_type == "activity" && slug.current == $slug][0] {    _id,    title,    image,    description,    price,    currency,    duration,    meetingPoint,    cancellationPolicy,    highlights,    whatToBring  }
export type QUERY_ACTIVITYResult = {
  _id: string;
  title: string | null;
  image: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }> | null;
  description: string | null;
  price: number | null;
  currency: 'AUD' | 'IDR' | 'USD' | null;
  duration: string | null;
  meetingPoint: string | null;
  cancellationPolicy: null;
  highlights: Array<string> | null;
  whatToBring: Array<string> | null;
} | null;

// Source: ./app/(frontend)/components/all-activities.tsx
// Variable: QUERY_ACTIVITIES
// Query: *[_type == 'activity'] | order(_createdAt desc) {    _id,    title,    "slug": slug.current,    price,    currency,    description,    "destination": destination->{      name,      "slug": slug.current,      },    "categories": categories[]->{      name      },    "image": image[0]  }
export type QUERY_ACTIVITIESResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  currency: 'AUD' | 'IDR' | 'USD' | null;
  description: string | null;
  destination: {
    name: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    name: string | null;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  } | null;
}>;

// Source: ./app/(frontend)/components/destinations.tsx
// Variable: QUERY_DESTINATIONS
// Query: *[_type == 'destination'] | order(_createdAt desc) {    _id,    name,    description,    "slug": slug.current,    image  }
export type QUERY_DESTINATIONSResult = Array<{
  _id: string;
  name: string | null;
  description: string | null;
  slug: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
}>;

// Source: ./app/(frontend)/components/popular-activities.tsx
// Variable: QUERY_POPULAR_ACTIVITIES
// Query: *[_type == 'activity' && isPopular == true] | order(_createdAt desc) [0...5] {    _id,    title,    "slug": slug.current,    price,    currency,    description,    "destination": destination->{      name,      "slug": slug.current,      },    "categories": categories[]->{      name      },    "image": image[0],  }
export type QUERY_POPULAR_ACTIVITIESResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  price: number | null;
  currency: 'AUD' | 'IDR' | 'USD' | null;
  description: string | null;
  destination: {
    name: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    name: string | null;
  }> | null;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  } | null;
}>;

declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "activity" && slug.current == $slug][0] {\n    _id,\n    title,\n    image,\n    description,\n    price,\n    currency,\n    duration,\n    meetingPoint,\n    cancellationPolicy,\n    highlights,\n    whatToBring\n  }\n': QUERY_ACTIVITYResult;
    '\n    *[_type == \'activity\'] | order(_createdAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    currency,\n    description,\n    "destination": destination->{\n      name,\n      "slug": slug.current,\n      },\n    "categories": categories[]->{\n      name\n      },\n    "image": image[0]\n  }': QUERY_ACTIVITIESResult;
    '\n    *[_type == \'destination\'] | order(_createdAt desc) {\n    _id,\n    name,\n    description,\n    "slug": slug.current,\n    image\n  }': QUERY_DESTINATIONSResult;
    '\n    *[_type == \'activity\' && isPopular == true] | order(_createdAt desc) [0...5] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    currency,\n    description,\n    "destination": destination->{\n      name,\n      "slug": slug.current,\n      },\n    "categories": categories[]->{\n      name\n      },\n    "image": image[0],\n  }': QUERY_POPULAR_ACTIVITIESResult;
  }
}
